# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'XMCallKit' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for XMCallKit

  target 'XMCallKitTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'XMCallKitUITests' do
    inherit! :search_paths
    # Pods for testing
  end

pod 'MJExtension'
pod 'Masonry'
pod 'AgoraRtcEngine_iOS'
pod 'YLGIFImage' #异步方式实现突Gif突破编码、显示，低内存占用.  
end
